#!/usr/bin/env python3

from pathlib import Path

import typer as ty
from result import is_err

from lib import Gh
from typings import get_settings

from rich.console import Console
from rich.markdown import Markdown

console = Console()


settings_candidate = get_settings(Path("lmist.env"))

if is_err(settings_candidate):
    print("error getting settings")
    print(settings_candidate.err())
    exit(1)

settings = settings_candidate.ok_value

gh = Gh(settings)

cli = ty.Typer(
    name="sparse"
)

@cli.command()
def main():
    repo = gh.g.get_repo('whoislou/full-stack-fastapi-template')
    contents = repo.get_contents('README.md')
    decoded = contents.decoded_content.decode('utf-8')
    md = Markdown(decoded)
    console.print(md)


if __name__ == "__main__":
    cli()